### ISSUE TITLE
JavaScript interview questions

### ISSUE THREAD

**Issue by magaNasib** [isbendiyarovanezrin/JavaScriptQuestionsAndAnswers#8]

**Comment by isbendiyarovanezrin** [comment]
@magaNasib, boş issue?

**Comment by magaNasib** [comment]
> @magaNasib, boş issue?

@isbendiyarovanezrin daha sonra oxumaq üçün save etmək istədim. Telefonda biraz qarışıqdı deyə belə alındı))
